services:
  mongo:
    image: mongo:7
    container_name: authsphere-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: authsphere-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/authsphere
      JWT_SECRET: docker_local_change_me
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_SECRET: docker_local_refresh_change_me
      JWT_REFRESH_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:5173
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: authsphere-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api/v1
    depends_on:
      - backend

volumes:
  mongo-data:
